### ISSUE TITLE
Missing manifest for dataset

### ISSUE THREAD

**Issue by kabilar** [datajoint/djarchive-client#4]
Hi @ixcat , dataset/revision `workflow-calcium-imaging-test-set` / `0_1_0a2` is missing a manifest, resulting in the error below.  How should we go about creating and uploading the manifest for this dataset?

```
> djarchive download workflow-calcium-imaging-test-set 0_1_0a2 ./workflow-calcium-imaging-test-set-0_1_0a2

fetching & loading dataset manifest

Traceback (most recent call last):
  File "/opt/miniconda3/envs/djarchive/bin/djarchive", line 173, in <module>
    actions[action][0](*sys.argv[2:])
  File "/opt/miniconda3/envs/djarchive/bin/djarchive", line 107, in download
    client().download(*args, create_target=True, display_progress=True)
  File "/opt/miniconda3/envs/djarchive/lib/python3.7/site-packages/djarchive_client/__init__.py", line 322, in download
    if not self.client.stat_object(self.bucket, ssubp):
  File "/opt/miniconda3/envs/djarchive/lib/python3.7/site-packages/minio/api.py", line 1911, in stat_object
    query_params=query_params,
  File "/opt/miniconda3/envs/djarchive/lib/python3.7/site-packages/minio/api.py", line 422, in _execute
    no_body_trace=no_body_trace,
  File "/opt/miniconda3/envs/djarchive/lib/python3.7/site-packages/minio/api.py", line 396, in _url_open
    raise response_error

minio.error.S3Error: S3 operation failed; code: NoSuchKey, 
message: Object does not exist, 
resource: /djhub.vathes.datapub.elements/workflow-calcium-imaging-test-set/0_1_0a2/djarchive-manifest.csv, 
request_id: 16A2970480FB3ADF, 
host_id: None, 
bucket_name: djhub.vathes.datapub.elements, 
object_name: workflow-calcium-imaging-test-set/0_1_0a2/djarchive-manifest.csv
```

Thanks!

**Comment by kabilar** [comment]
@GeetikaSi

**Comment by ixcat** [comment]
Hi @kabilar - this normally would mean an incomplete/corrupted upload since the manifest is added as the last part of the process - however, manifest support was added later in the initial development cycle, so it's possible that this set was uploaded using the old, no-manifest logic.

If this is the case, you can remove whatever manifest is present and  'djarchive manifest' on a system with the full dataset and manually use an S3 client to copy the manifest into place (expected location give in the error message), or alternately reupload the full set as a new revision

**Comment by ixcat** [comment]
discussed with @kabilar - this dataset appears to predate the manifest support; advised on update procedure.

**Comment by kabilar** [comment]
Thank you @ixcat.  I have added a manifest for this dataset/revision (`workflow-calcium-imaging-test-set` / `0_1_0a2`) and the download is now running.
